### PR TITLE
Make webdataset creator faster

### PR DESCRIPTION
**Pull request by t-schanz**
Faster iterator for getting all files.

### CODE REVIEW

**Review by smalldatalooser — APPROVED** [review]
Good Idea!

**Comment by tmachnitzki** [comment]
The code is still too slow. 
We need to convert it to a pipeline approach, where we do not first gather all files and then iterate over the list, but rather just append png files whenever we find them directly.

**Comment by tmachnitzki** [comment]
The script is running now and seems to work.

**Comment by tmachnitzki** [comment]
This can only be merged, after #43 has been merged

**Pull request merged**
